/* Generated by scripts/build-cosmic-web.mjs from Tully 2015 (AJ 149, 171) and Karachentsev et al. 2013 (AJ 145, 101). Do not edit. */

export interface GenStructure {
  id: string;
  name: string;
  /** "cluster": rich cluster from Tully's 2MRS groups; "group": nearby group with measured distances. */
  kind: "cluster" | "group";
  /** Render axes, millions of light-years. */
  position: [number, number, number];
  distanceMly: number;
  radiusMly: number;
  /** Members in the catalogue (2MRS galaxies brighter than Ks 11.75, or all known nearby galaxies). */
  members: number;
  sigmaKms?: number;
  massSolar?: number;
  velocityKms?: number;
  supercluster: string | null;
}

export interface GenSupercluster {
  id: string;
  name: string;
  position: [number, number, number];
  distanceMly: number;
  radiusMly: number;
  groups: number;
  galaxies: number;
  /** Inside Laniakea, our home basin of attraction (Tully et al. 2014). */
  laniakea: boolean;
}

/** Index in this list = the structure index stored per galaxy in cosmic-web.bin. */
export const GEN_STRUCTURES: GenStructure[] = [
  {
    "id": "virgo-cluster",
    "name": "Virgo Cluster",
    "kind": "cluster",
    "position": [
      -52,
      13.22,
      1.9
    ],
    "distanceMly": 53.7,
    "radiusMly": 6.26,
    "members": 197,
    "sigmaKms": 670,
    "massSolar": 930000000000000,
    "velocityKms": 1491,
    "supercluster": "local-supercluster"
  },
  {
    "id": "fornax-cluster",
    "name": "Fornax Cluster",
    "kind": "cluster",
    "position": [
      28.49,
      -46.68,
      -22.39
    ],
    "distanceMly": 59.1,
    "radiusMly": 3.66,
    "members": 49,
    "sigmaKms": 301,
    "massSolar": 110000000000000,
    "velocityKms": 1362,
    "supercluster": "fornax-eridanus"
  },
  {
    "id": "ursa-major-cluster",
    "name": "Ursa Major Cluster",
    "kind": "cluster",
    "position": [
      -30.31,
      31.13,
      -13.48
    ],
    "distanceMly": 45.5,
    "radiusMly": 3.24,
    "members": 65,
    "sigmaKms": 209,
    "massSolar": 73000000000000,
    "velocityKms": 1054,
    "supercluster": "local-supercluster"
  },
  {
    "id": "antlia-cluster",
    "name": "Antlia Cluster",
    "kind": "cluster",
    "position": [
      -106.78,
      -92.8,
      -8.72
    ],
    "distanceMly": 141.7,
    "radiusMly": 4.18,
    "members": 47,
    "sigmaKms": 502,
    "massSolar": 280000000000000,
    "velocityKms": 3257,
    "supercluster": "hydra-centaurus"
  },
  {
    "id": "centaurus-cluster",
    "name": "Centaurus Cluster (Abell 3526)",
    "kind": "cluster",
    "position": [
      -123.98,
      -91.03,
      68.18
    ],
    "distanceMly": 168.2,
    "radiusMly": 6.61,
    "members": 113,
    "sigmaKms": 822,
    "massSolar": 1400000000000000,
    "velocityKms": 3873,
    "supercluster": "hydra-centaurus"
  },
  {
    "id": "hydra-cluster",
    "name": "Hydra Cluster (Abell 1060)",
    "kind": "cluster",
    "position": [
      -147.57,
      -98.26,
      -18.73
    ],
    "distanceMly": 178.3,
    "radiusMly": 5.21,
    "members": 85,
    "sigmaKms": 648,
    "massSolar": 590000000000000,
    "velocityKms": 4099,
    "supercluster": "hydra-centaurus"
  },
  {
    "id": "norma-cluster",
    "name": "Norma Cluster (Abell 3627)",
    "kind": "cluster",
    "position": [
      -47.82,
      -140.39,
      165.97
    ],
    "distanceMly": 222.6,
    "radiusMly": 8.38,
    "members": 167,
    "sigmaKms": 957,
    "massSolar": 2400000000000000,
    "velocityKms": 5118,
    "supercluster": "pavo-indus-norma"
  },
  {
    "id": "pavo-ii-cluster",
    "name": "Pavo II Cluster",
    "kind": "cluster",
    "position": [
      16.97,
      -125.62,
      149.03
    ],
    "distanceMly": 195.7,
    "radiusMly": 5.35,
    "members": 66,
    "sigmaKms": 473,
    "massSolar": 390000000000000,
    "velocityKms": 4501,
    "supercluster": "pavo-indus-norma"
  },
  {
    "id": "abell-262",
    "name": "Abell 262",
    "kind": "cluster",
    "position": [
      144.66,
      79.45,
      -119.79
    ],
    "distanceMly": 203.9,
    "radiusMly": 5.07,
    "members": 63,
    "sigmaKms": 520,
    "massSolar": 380000000000000,
    "velocityKms": 4687,
    "supercluster": "perseus-pisces"
  },
  {
    "id": "ngc-383-group",
    "name": "NGC 383 Group (Pisces)",
    "kind": "cluster",
    "position": [
      171.28,
      84.24,
      -94.68
    ],
    "distanceMly": 213.1,
    "radiusMly": 4.9,
    "members": 48,
    "sigmaKms": 432,
    "massSolar": 290000000000000,
    "velocityKms": 4900,
    "supercluster": "perseus-pisces"
  },
  {
    "id": "perseus-cluster",
    "name": "Perseus Cluster (Abell 426)",
    "kind": "cluster",
    "position": [
      111.28,
      87.32,
      -180.8
    ],
    "distanceMly": 229.6,
    "radiusMly": 8.25,
    "members": 180,
    "sigmaKms": 962,
    "massSolar": 2200000000000000,
    "velocityKms": 5281,
    "supercluster": "perseus-pisces"
  },
  {
    "id": "abell-3574",
    "name": "Abell 3574",
    "kind": "cluster",
    "position": [
      -164.6,
      -66.14,
      120.37
    ],
    "distanceMly": 214.4,
    "radiusMly": 5.29,
    "members": 45,
    "sigmaKms": 440,
    "massSolar": 260000000000000,
    "velocityKms": 4929,
    "supercluster": null
  },
  {
    "id": "leo-cluster",
    "name": "Leo Cluster (Abell 1367)",
    "kind": "cluster",
    "position": [
      -285.01,
      87.54,
      -59.12
    ],
    "distanceMly": 304,
    "radiusMly": 6.78,
    "members": 61,
    "sigmaKms": 707,
    "massSolar": 720000000000000,
    "velocityKms": 6987,
    "supercluster": "coma-supercluster"
  },
  {
    "id": "coma-cluster",
    "name": "Coma Cluster (Abell 1656)",
    "kind": "cluster",
    "position": [
      -272.31,
      165.47,
      6.38
    ],
    "distanceMly": 318.7,
    "radiusMly": 9.26,
    "members": 136,
    "sigmaKms": 886,
    "massSolar": 2100000000000000,
    "velocityKms": 7331,
    "supercluster": "coma-supercluster"
  },
  {
    "id": "abell-496",
    "name": "Abell 496",
    "kind": "cluster",
    "position": [
      160,
      -248.62,
      -325.33
    ],
    "distanceMly": 439.6,
    "radiusMly": 8.45,
    "members": 54,
    "sigmaKms": 529,
    "massSolar": 910000000000000,
    "velocityKms": 10106,
    "supercluster": null
  },
  {
    "id": "ophiuchus-cluster",
    "name": "Ophiuchus Cluster",
    "kind": "cluster",
    "position": [
      -75.34,
      -3.24,
      388.89
    ],
    "distanceMly": 396.1,
    "radiusMly": 9.11,
    "members": 66,
    "sigmaKms": 976,
    "massSolar": 2300000000000000,
    "velocityKms": 9112,
    "supercluster": "ophiuchus-supercluster"
  },
  {
    "id": "abell-2199",
    "name": "Abell 2199",
    "kind": "cluster",
    "position": [
      -122.08,
      357.17,
      159.05
    ],
    "distanceMly": 409.6,
    "radiusMly": 9.36,
    "members": 81,
    "sigmaKms": 740,
    "massSolar": 1900000000000000,
    "velocityKms": 9424,
    "supercluster": "hercules-supercluster"
  },
  {
    "id": "hercules-cluster",
    "name": "Hercules Cluster (Abell 2151)",
    "kind": "cluster",
    "position": [
      -233.07,
      303.26,
      328.78
    ],
    "distanceMly": 504.4,
    "radiusMly": 12.27,
    "members": 86,
    "sigmaKms": 1261,
    "massSolar": 7100000000000000,
    "velocityKms": 11603,
    "supercluster": "hercules-supercluster"
  },
  {
    "id": "abell-3716",
    "name": "Abell 3716",
    "kind": "cluster",
    "position": [
      260.64,
      -345.31,
      454.37
    ],
    "distanceMly": 627.4,
    "radiusMly": 17.27,
    "members": 52,
    "sigmaKms": 916,
    "massSolar": 4700000000000000,
    "velocityKms": 14434,
    "supercluster": null
  },
  {
    "id": "abell-3558",
    "name": "Abell 3558 (Shapley core)",
    "kind": "cluster",
    "position": [
      -522.11,
      -235.83,
      334.76
    ],
    "distanceMly": 663.5,
    "radiusMly": 16.89,
    "members": 55,
    "sigmaKms": 1002,
    "massSolar": 4900000000000000,
    "velocityKms": 15265,
    "supercluster": null
  },
  {
    "id": "local-group",
    "name": "Local Group",
    "kind": "group",
    "position": [
      1.015,
      0.679,
      -0.476
    ],
    "distanceMly": 1.31,
    "radiusMly": 1.53,
    "members": 71,
    "supercluster": "local-supercluster"
  },
  {
    "id": "m81-group",
    "name": "M81 Group",
    "kind": "group",
    "position": [
      -3.726,
      9.482,
      -6.558
    ],
    "distanceMly": 12.12,
    "radiusMly": 1.19,
    "members": 40,
    "supercluster": "local-supercluster"
  },
  {
    "id": "centaurus-a-group",
    "name": "Centaurus A Group",
    "kind": "group",
    "position": [
      -8.008,
      -6.341,
      6.326
    ],
    "distanceMly": 12.01,
    "radiusMly": 1.76,
    "members": 31,
    "supercluster": "local-supercluster"
  },
  {
    "id": "m83-group",
    "name": "M83 Group",
    "kind": "group",
    "position": [
      -12.042,
      -5.16,
      7.945
    ],
    "distanceMly": 15.32,
    "radiusMly": 1.88,
    "members": 16,
    "supercluster": "local-supercluster"
  },
  {
    "id": "sculptor-group",
    "name": "Sculptor Group",
    "kind": "group",
    "position": [
      11.309,
      -5.299,
      0.203
    ],
    "distanceMly": 12.49,
    "radiusMly": 1.84,
    "members": 8,
    "supercluster": "local-supercluster"
  },
  {
    "id": "ic342-group",
    "name": "IC 342 / Maffei Group",
    "kind": "group",
    "position": [
      2.588,
      7.034,
      -6.701
    ],
    "distanceMly": 10.05,
    "radiusMly": 1.9,
    "members": 16,
    "supercluster": "local-supercluster"
  },
  {
    "id": "m94-group",
    "name": "M94 Group (Canes Venatici I)",
    "kind": "group",
    "position": [
      -11.156,
      9.61,
      -1.682
    ],
    "distanceMly": 14.82,
    "radiusMly": 2.32,
    "members": 18,
    "supercluster": "local-supercluster"
  },
  {
    "id": "m106-group",
    "name": "M106 Group",
    "kind": "group",
    "position": [
      -17.4,
      17.488,
      -5.75
    ],
    "distanceMly": 25.33,
    "radiusMly": 2.18,
    "members": 21,
    "supercluster": "local-supercluster"
  },
  {
    "id": "m101-group",
    "name": "M101 Group",
    "kind": "group",
    "position": [
      -11.905,
      20.759,
      -1.285
    ],
    "distanceMly": 23.96,
    "radiusMly": 1.17,
    "members": 6,
    "supercluster": "local-supercluster"
  },
  {
    "id": "leo-i-group",
    "name": "Leo I Group (M96)",
    "kind": "group",
    "position": [
      -31.384,
      2.659,
      -12.456
    ],
    "distanceMly": 33.87,
    "radiusMly": 1.81,
    "members": 42,
    "supercluster": "local-supercluster"
  },
  {
    "id": "sombrero-group",
    "name": "Sombrero Group",
    "kind": "group",
    "position": [
      -27.36,
      -4.385,
      6.394
    ],
    "distanceMly": 28.44,
    "radiusMly": 4.35,
    "members": 12,
    "supercluster": "local-supercluster"
  }
];

/** Index in this list = the supercluster index stored per galaxy in cosmic-web.bin. */
export const GEN_SUPERCLUSTERS: GenSupercluster[] = [
  {
    "id": "local-supercluster",
    "name": "Local (Virgo) Supercluster",
    "position": [
      -65.48,
      14.53,
      6.64
    ],
    "distanceMly": 67,
    "radiusMly": 115,
    "groups": 54,
    "galaxies": 729,
    "laniakea": true
  },
  {
    "id": "perseus-pisces",
    "name": "Perseus–Pisces Supercluster",
    "position": [
      136,
      75.98,
      -143.22
    ],
    "distanceMly": 212,
    "radiusMly": 124,
    "groups": 38,
    "galaxies": 694,
    "laniakea": false
  },
  {
    "id": "hydra-centaurus",
    "name": "Hydra–Centaurus Supercluster",
    "position": [
      -118.18,
      -91.8,
      24.53
    ],
    "distanceMly": 152,
    "radiusMly": 109,
    "groups": 36,
    "galaxies": 455,
    "laniakea": true
  },
  {
    "id": "pavo-indus-norma",
    "name": "Norma & Pavo–Indus Superclusters",
    "position": [
      0.35,
      -131.65,
      156.99
    ],
    "distanceMly": 205,
    "radiusMly": 139,
    "groups": 24,
    "galaxies": 417,
    "laniakea": true
  },
  {
    "id": "fornax-eridanus",
    "name": "Fornax–Eridanus Cloud",
    "position": [
      33.06,
      -40,
      -13.56
    ],
    "distanceMly": 54,
    "radiusMly": 81,
    "groups": 24,
    "galaxies": 212,
    "laniakea": true
  },
  {
    "id": "coma-supercluster",
    "name": "Coma Supercluster",
    "position": [
      -281.92,
      133.48,
      -22.18
    ],
    "distanceMly": 313,
    "radiusMly": 68,
    "groups": 12,
    "galaxies": 306,
    "laniakea": false
  },
  {
    "id": "hercules-supercluster",
    "name": "Hercules Supercluster",
    "position": [
      -154.38,
      334.69,
      221.89
    ],
    "distanceMly": 430,
    "radiusMly": 156,
    "groups": 14,
    "galaxies": 259,
    "laniakea": false
  },
  {
    "id": "ophiuchus-supercluster",
    "name": "Ophiuchus Supercluster",
    "position": [
      -74.05,
      2.47,
      387.11
    ],
    "distanceMly": 394,
    "radiusMly": 29,
    "groups": 5,
    "galaxies": 94,
    "laniakea": false
  }
];

export const COSMIC_WEB_GALAXIES = 43704;
