// Generated by scripts/build-solar-system.mjs — do not edit.
// Sources: JPL Small-Body Database, JPL Horizons, CelesTrak. Built 2026-09-25.
/* eslint-disable */

export interface SbdbPhysical {
  diameterKm?: number;
  extent?: string;
  rotationHours?: number;
  albedo?: number;
  H?: number;
  gm?: number;
  density?: number;
}

/** Heliocentric osculating elements, ecliptic J2000 (JPL SBDB). Angles in degrees, times as JD (TDB). */
export interface SbdbBody {
  designation: string;
  kind: string;
  orbitClass?: string;
  epoch: number;
  e: number;
  q: number;
  a?: number;
  i: number;
  om: number;
  w: number;
  tp: number;
  periodDays?: number;
  phys: SbdbPhysical;
  discovery?: { date: string; by?: string; site?: string };
}

/** Planet-centred orbit, ecliptic J2000, with secular rates (deg/day) fitted to JPL Horizons. */
export interface MoonOrbit {
  epoch: number;
  aKm: number;
  e: number;
  i: number;
  om: number;
  dOm: number;
  w: number;
  dW: number;
  /** Mean longitude Ω + ω + M and its rate. */
  L: number;
  dL: number;
}

export const SMALL_BODY_EPOCH_JD = 2461200.5;
export const SMALL_BODY_COUNTS = { core: 26832, more: 43847, byClass: [36780,623,4069,1218,11628,8015,1045,712,3128,3347,100,14] };

export const SBDB_BODIES: Record<string, SbdbBody> = {
 "ceres": {
  "designation": "1 Ceres (A801 AA)",
  "kind": "an",
  "orbitClass": "Main-belt Asteroid",
  "epoch": 2461200.5,
  "e": 0.079692295,
  "q": 2.545159361,
  "i": 10.588028,
  "om": 80.248627,
  "w": 73.294215,
  "tp": 2461599.841467,
  "a": 2.765552595,
  "periodDays": 1679.9,
  "phys": {
   "diameterKm": 939.4,
   "extent": "964.4 x 964.2 x 891.8",
   "rotationHours": 9.07417,
   "albedo": 0.09,
   "H": 3.34,
   "gm": 62.6284,
   "density": 2.162
  },
  "discovery": {
   "date": "1801-Jan-01",
   "by": "Piazzi, G.",
   "site": "Palermo"
  }
 },
 "eris": {
  "designation": "136199 Eris (2003 UB313)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.438238535,
  "q": 38.162673535,
  "i": 43.925828,
  "om": 36.00477,
  "w": 150.794924,
  "tp": 2545407.716847,
  "a": 67.933946879,
  "periodDays": 204516.7,
  "phys": {
   "rotationHours": 25.9,
   "H": -1.26
  },
  "discovery": {
   "date": "2003-Oct-21",
   "by": "Brown, M. E., Trujillo, C. A., Rabinowitz, D.",
   "site": "Palomar"
  }
 },
 "haumea": {
  "designation": "136108 Haumea (2003 EL61)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.194443015,
  "q": 34.687517581,
  "i": 28.208474,
  "om": 121.786056,
  "w": 240.690547,
  "tp": 2500416.599615,
  "a": 43.060290237,
  "periodDays": 103208.1,
  "phys": {
   "rotationHours": 3.9154,
   "H": 0.14
  },
  "discovery": {
   "date": "2003-Mar-07",
   "by": "Aceituno, F. J., Santos-Sanz, P., Ortiz, J. L.",
   "site": "Sierra Nevada"
  }
 },
 "makemake": {
  "designation": "136472 Makemake (2005 FY9)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.158888995,
  "q": 38.330213382,
  "i": 29.027856,
  "om": 79.294834,
  "w": 297.092273,
  "tp": 2408158.694099,
  "a": 45.570933173,
  "periodDays": 112364.8,
  "phys": {
   "rotationHours": 22.8266,
   "H": -0.25
  },
  "discovery": {
   "date": "2005-Mar-31",
   "by": "Brown, M. E., Trujillo, C. A., Rabinowitz, D.",
   "site": "Palomar"
  }
 },
 "gonggong": {
  "designation": "225088 Gonggong (2007 OR10)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.504251,
  "q": 33.149082641,
  "i": 30.899067,
  "om": 336.838316,
  "w": 206.623284,
  "tp": 2399252.724654,
  "a": 66.866665678,
  "periodDays": 199716,
  "phys": {
   "rotationHours": 22.4,
   "H": 1.82
  },
  "discovery": {
   "date": "2007-Jul-17",
   "by": "Schwamb, M. E., Brown, M. E., Rabinowitz, D.",
   "site": "Palomar"
  }
 },
 "quaoar": {
  "designation": "50000 Quaoar (2002 LM60)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.035200237,
  "q": 41.637068857,
  "i": 7.991576,
  "om": 188.919125,
  "w": 163.209051,
  "tp": 2480516.376493,
  "a": 43.156176488,
  "periodDays": 103553,
  "phys": {
   "rotationHours": 8.84,
   "H": 2.41
  },
  "discovery": {
   "date": "2002-Jun-04",
   "by": "Trujillo, C. A., Brown, M. E.",
   "site": "Palomar"
  }
 },
 "orcus": {
  "designation": "90482 Orcus (2004 DW)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.220524063,
  "q": 30.693319044,
  "i": 20.55681,
  "om": 268.405352,
  "w": 73.568486,
  "tp": 2504046.134962,
  "a": 39.376865379,
  "periodDays": 90252.7,
  "phys": {
   "rotationHours": 13.188,
   "H": 2.13
  },
  "discovery": {
   "date": "2004-Feb-17",
   "by": "Brown, M., Trujillo, C.",
   "site": "Palomar"
  }
 },
 "sedna": {
  "designation": "90377 Sedna (2003 VB12)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.859882459,
  "q": 76.184643646,
  "i": 11.925276,
  "om": 144.506166,
  "w": 311.098773,
  "tp": 2479264.750687,
  "a": 543.71952891,
  "periodDays": 4630851.2,
  "phys": {
   "rotationHours": 10.273,
   "H": 1.5
  },
  "discovery": {
   "date": "2003-Nov-14",
   "by": "Brown, M. E., Trujillo, C. A., Rabinowitz, D.",
   "site": "Palomar"
  }
 },
 "arrokoth": {
  "designation": "486958 Arrokoth (2014 MU69)",
  "kind": "an",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2461200.5,
  "e": 0.035557176,
  "q": 42.486193058,
  "i": 2.450614,
  "om": 159.037727,
  "w": 188.850746,
  "tp": 2475741.403873,
  "a": 44.05257836,
  "periodDays": 106796.1,
  "phys": {
   "rotationHours": 15.918,
   "H": 11.06
  },
  "discovery": {
   "date": "2014-Jun-26",
   "by": "Hubble Space Telescope",
   "site": "HST"
  }
 },
 "farfarout": {
  "designation": "(2018 AG37)",
  "kind": "au",
  "orbitClass": "TransNeptunian Object",
  "epoch": 2458539.5,
  "e": 0.655445657,
  "q": 27.625754208,
  "i": 18.674897,
  "om": 68.356497,
  "w": 231.721381,
  "tp": 2584246.201082,
  "a": 80.178220819,
  "periodDays": 262230.4,
  "phys": {
   "H": 4.22
  }
 },
 "vesta": {
  "designation": "4 Vesta (A807 FA)",
  "kind": "an",
  "orbitClass": "Main-belt Asteroid",
  "epoch": 2461200.5,
  "e": 0.090203744,
  "q": 2.148361915,
  "i": 7.143926,
  "om": 103.701293,
  "w": 151.468648,
  "tp": 2460901.58738,
  "a": 2.361365965,
  "periodDays": 1325.4,
  "phys": {
   "diameterKm": 522.77,
   "extent": "569.24 x 554.48 x 452.66",
   "rotationHours": 5.3421276322,
   "albedo": 0.4228,
   "H": 3.25,
   "gm": 17.2882844,
   "density": 3.46
  },
  "discovery": {
   "date": "1807-Mar-29",
   "by": "Olbers, H. W.",
   "site": "Bremen"
  }
 },
 "pallas": {
  "designation": "2 Pallas (A802 FA)",
  "kind": "an",
  "orbitClass": "Main-belt Asteroid",
  "epoch": 2461200.5,
  "e": 0.2307001,
  "q": 2.130621471,
  "i": 34.932793,
  "om": 172.886619,
  "w": 310.969916,
  "tp": 2461695.031164,
  "a": 2.769559011,
  "periodDays": 1683.5,
  "phys": {
   "diameterKm": 513,
   "extent": "568x532x448",
   "rotationHours": 7.8132214,
   "albedo": 0.155,
   "H": 4.12,
   "gm": 13.63,
   "density": 2.89
  },
  "discovery": {
   "date": "1802-Mar-28",
   "by": "Olbers, H. W.",
   "site": "Bremen"
  }
 },
 "hygiea": {
  "designation": "10 Hygiea (A849 GA)",
  "kind": "an",
  "orbitClass": "Main-belt Asteroid",
  "epoch": 2461200.5,
  "e": 0.106709274,
  "q": 2.814735882,
  "i": 3.82953,
  "om": 283.119893,
  "w": 312.424239,
  "tp": 2461813.200829,
  "a": 3.150974034,
  "periodDays": 2043,
  "phys": {
   "diameterKm": 407.12,
   "rotationHours": 13.828,
   "albedo": 0.0717,
   "H": 5.65,
   "gm": 7
  },
  "discovery": {
   "date": "1849-Apr-12",
   "by": "De Gasparis, A.",
   "site": "Naples"
  }
 },
 "psyche": {
  "designation": "16 Psyche (A852 FA)",
  "kind": "an",
  "orbitClass": "Main-belt Asteroid",
  "epoch": 2461200.5,
  "e": 0.134932474,
  "q": 2.530945766,
  "i": 3.098749,
  "om": 149.975386,
  "w": 230.032678,
  "tp": 2460795.475337,
  "a": 2.925720466,
  "periodDays": 1827.9,
  "phys": {
   "diameterKm": 222,
   "extent": "278 x 238 x 171",
   "rotationHours": 4.196,
   "albedo": 0.1203,
   "H": 6.2,
   "gm": 1.601,
   "density": 4.172
  },
  "discovery": {
   "date": "1852-Mar-17",
   "by": "De Gasparis, A.",
   "site": "Naples"
  }
 },
 "eros": {
  "designation": "433 Eros (A898 PA)",
  "kind": "an",
  "orbitClass": "Amor",
  "epoch": 2461200.5,
  "e": 0.222877963,
  "q": 1.133233328,
  "i": 10.828544,
  "om": 304.267971,
  "w": 178.918132,
  "tp": 2461088.813494,
  "a": 1.458243717,
  "periodDays": 643.2,
  "phys": {
   "diameterKm": 16.84,
   "extent": "34.4x11.2x11.2",
   "rotationHours": 5.27,
   "albedo": 0.25,
   "H": 10.4,
   "gm": 0.0004463,
   "density": 2.67
  },
  "discovery": {
   "date": "1898-Aug-13",
   "by": "Witt, G.",
   "site": "Berlin"
  }
 },
 "bennu": {
  "designation": "101955 Bennu (1999 RQ36)",
  "kind": "an",
  "orbitClass": "Apollo",
  "epoch": 2455562.5,
  "e": 0.203745076,
  "q": 0.8968944,
  "i": 6.034944,
  "om": 2.060866,
  "w": 66.223061,
  "tp": 2455439.141941,
  "a": 1.126391026,
  "periodDays": 436.6,
  "phys": {
   "diameterKm": 0.48444,
   "extent": "0.5047 x 0.4918 x 0.4567",
   "rotationHours": 4.296061,
   "albedo": 0.044,
   "H": 20.21,
   "gm": 4.8904e-9,
   "density": 1.194
  },
  "discovery": {
   "date": "1999-Sep-11",
   "by": "LINEAR",
   "site": "Socorro"
  }
 },
 "ryugu": {
  "designation": "162173 Ryugu (1999 JU3)",
  "kind": "an",
  "orbitClass": "Apollo",
  "epoch": 2461200.5,
  "e": 0.191073005,
  "q": 0.963366474,
  "i": 5.866442,
  "om": 251.289712,
  "w": 211.608994,
  "tp": 2461118.296422,
  "a": 1.190918933,
  "periodDays": 474.7,
  "phys": {
   "diameterKm": 0.896,
   "extent": "1.004x0.876",
   "rotationHours": 7.63262,
   "albedo": 0.045,
   "H": 19.55,
   "gm": 3e-8,
   "density": 1.19
  },
  "discovery": {
   "date": "1999-May-10",
   "by": "LINEAR",
   "site": "Socorro"
  }
 },
 "itokawa": {
  "designation": "25143 Itokawa (1998 SF36)",
  "kind": "an",
  "orbitClass": "Apollo",
  "epoch": 2461200.5,
  "e": 0.280177641,
  "q": 0.953082438,
  "i": 1.620941,
  "om": 69.074497,
  "w": 162.840902,
  "tp": 2460936.702994,
  "a": 1.324052284,
  "periodDays": 556.5,
  "phys": {
   "diameterKm": 0.33,
   "extent": "0.535x0.294x0.209",
   "rotationHours": 12.132,
   "H": 19.26,
   "gm": 2.1e-9,
   "density": 1.9
  },
  "discovery": {
   "date": "1998-Sep-26",
   "by": "LINEAR",
   "site": "Socorro"
  }
 },
 "apophis": {
  "designation": "99942 Apophis (2004 MN4)",
  "kind": "an",
  "orbitClass": "Aten",
  "epoch": 2461200.5,
  "e": 0.191149228,
  "q": 0.746050968,
  "i": 3.340997,
  "om": 203.893651,
  "w": 126.679571,
  "tp": 2461042.919201,
  "a": 0.922359221,
  "periodDays": 323.6,
  "phys": {
   "diameterKm": 0.34,
   "rotationHours": 30.56,
   "albedo": 0.35,
   "H": 19.09
  },
  "discovery": {
   "date": "2004-Jun-19",
   "by": "Tholen, D. J.",
   "site": "Kitt Peak"
  }
 },
 "didymos": {
  "designation": "65803 Didymos (1996 GT)",
  "kind": "an",
  "orbitClass": "Apollo",
  "epoch": 2461200.5,
  "e": 0.383123324,
  "q": 1.013349243,
  "i": 3.413877,
  "om": 72.985824,
  "w": 319.5807,
  "tp": 2461412.27778,
  "a": 1.642709609,
  "periodDays": 769,
  "phys": {
   "diameterKm": 0.78,
   "extent": "0.797 x 0.783 x 0.761",
   "rotationHours": 2.2593,
   "H": 18.11,
   "density": 2.17
  },
  "discovery": {
   "date": "1996-Apr-11",
   "by": "Spacewatch",
   "site": "Kitt Peak"
  }
 },
 "kamooalewa": {
  "designation": "469219 Kamo`oalewa (2016 HO3)",
  "kind": "an",
  "orbitClass": "Apollo",
  "epoch": 2461200.5,
  "e": 0.102238843,
  "q": 0.898488757,
  "i": 7.802614,
  "om": 65.593242,
  "w": 304.363213,
  "tp": 2461318.959559,
  "a": 1.000810462,
  "periodDays": 365.7,
  "phys": {
   "rotationHours": 0.467,
   "H": 24.31
  },
  "discovery": {
   "date": "2016-Apr-27",
   "by": "Pan-STARRS 1",
   "site": "Haleakala"
  }
 },
 "cruithne": {
  "designation": "3753 Cruithne (1986 TO)",
  "kind": "an",
  "orbitClass": "Aten",
  "epoch": 2461200.5,
  "e": 0.514903601,
  "q": 0.484027816,
  "i": 19.802381,
  "om": 126.188692,
  "w": 43.883016,
  "tp": 2461380.368896,
  "a": 0.997797174,
  "periodDays": 364.1,
  "phys": {
   "diameterKm": 2.071,
   "rotationHours": 27.3099,
   "albedo": 0.365,
   "H": 15.42
  },
  "discovery": {
   "date": "1986-Oct-10",
   "by": "Waldron, D.",
   "site": "Siding Spring"
  }
 },
 "patroclus": {
  "designation": "617 Patroclus (A906 UL)",
  "kind": "an",
  "orbitClass": "Jupiter Trojan",
  "epoch": 2461200.5,
  "e": 0.139146792,
  "q": 4.481580431,
  "i": 22.063591,
  "om": 44.349688,
  "w": 308.837728,
  "tp": 2460493.360075,
  "a": 5.205975174,
  "periodDays": 4338.6,
  "phys": {
   "diameterKm": 140.362,
   "rotationHours": 102.8,
   "albedo": 0.047,
   "H": 8.22
  },
  "discovery": {
   "date": "1906-Oct-17",
   "by": "Kopff, A.",
   "site": "Heidelberg"
  }
 },
 "chiron": {
  "designation": "2060 Chiron (1977 UB)",
  "kind": "an",
  "orbitClass": "Centaur",
  "epoch": 2461200.5,
  "e": 0.379765631,
  "q": 8.487453083,
  "i": 6.930574,
  "om": 209.296126,
  "w": 339.287833,
  "tp": 2468559.421163,
  "a": 13.684267609,
  "periodDays": 18489.7,
  "phys": {
   "diameterKm": 166,
   "rotationHours": 5.918,
   "albedo": 0.15,
   "H": 5.54
  },
  "discovery": {
   "date": "1977-Oct-18",
   "by": "Kowal, C.",
   "site": "Palomar"
  }
 },
 "halley": {
  "designation": "1P/Halley",
  "kind": "cn",
  "orbitClass": "Halley-type Comet*",
  "epoch": 2439875.5,
  "e": 0.967935996,
  "q": 0.574863831,
  "i": 162.19053,
  "om": 59.098947,
  "w": 112.241431,
  "tp": 2446469.973616,
  "a": 17.928635049,
  "periodDays": 27728,
  "phys": {
   "diameterKm": 11,
   "extent": "14.9x8.2",
   "albedo": 0.04
  },
  "discovery": {
   "date": "1758-Dec-25",
   "by": "Palitzsch, Johann Georg",
   "site": ""
  }
 },
 "encke": {
  "designation": "2P/Encke",
  "kind": "cn",
  "orbitClass": "Encke-type Comet",
  "epoch": 2460062.5,
  "e": 0.847027903,
  "q": 0.339482182,
  "i": 11.34227,
  "om": 334.045469,
  "w": 187.263043,
  "tp": 2460240.009057,
  "a": 2.219242526,
  "periodDays": 1207.6,
  "phys": {
   "diameterKm": 4.8,
   "rotationHours": 11.083,
   "albedo": 0.046
  },
  "discovery": {
   "date": "1786-Jan-17",
   "by": "Mechain, Pierre F. A.",
   "site": ""
  }
 },
 "churyumov-gerasimenko": {
  "designation": "67P/Churyumov-Gerasimenko",
  "kind": "cn",
  "orbitClass": "Jupiter-family Comet",
  "epoch": 2457305.5,
  "e": 0.640908131,
  "q": 1.243265641,
  "i": 7.040295,
  "om": 50.135574,
  "w": 12.79825,
  "tp": 2457247.588658,
  "a": 3.46224949,
  "periodDays": 2353.1,
  "phys": {
   "diameterKm": 3.4,
   "rotationHours": 12.76129,
   "gm": 6.622e-7,
   "density": 0.533
  },
  "discovery": {
   "date": "1969-Oct-22",
   "by": "Churyumov, Klim Ivanovic",
   "site": "Alma-Ata Observatory, Russia"
  }
 },
 "tempel-1": {
  "designation": "9P/Tempel 1",
  "kind": "cn",
  "orbitClass": "Jupiter-family Comet",
  "epoch": 2457470.5,
  "e": 0.509702833,
  "q": 1.54254047,
  "i": 10.473428,
  "om": 68.753575,
  "w": 179.197275,
  "tp": 2457603.070725,
  "a": 3.146133759,
  "periodDays": 2038.3,
  "phys": {
   "diameterKm": 6,
   "extent": "7.6x4.9",
   "rotationHours": 40.7,
   "albedo": 0.05
  },
  "discovery": {
   "date": "1867-Apr-03",
   "by": "Tempel, William",
   "site": "Marseilles, France"
  }
 },
 "hartley-2": {
  "designation": "103P/Hartley 2",
  "kind": "cn",
  "orbitClass": "Jupiter-family Comet",
  "epoch": 2457152.5,
  "e": 0.693597857,
  "q": 1.064947369,
  "i": 13.599468,
  "om": 219.742174,
  "w": 181.321844,
  "tp": 2457863.957983,
  "a": 3.475652487,
  "periodDays": 2366.8,
  "phys": {
   "diameterKm": 1.6,
   "rotationHours": 18.1
  },
  "discovery": {
   "date": "1986-Mar-15",
   "by": "Hartley, Malcolm",
   "site": "U. K. Schmidt Telescope Unit, Siding Spring"
  }
 },
 "swift-tuttle": {
  "designation": "109P/Swift-Tuttle",
  "kind": "cn",
  "orbitClass": "Halley-type Comet*",
  "epoch": 2450000.5,
  "e": 0.963225755,
  "q": 0.959516155,
  "i": 113.453817,
  "om": 139.381192,
  "w": 152.982168,
  "tp": 2448968.499785,
  "a": 26.092069498,
  "periodDays": 48681.2,
  "phys": {
   "diameterKm": 26
  },
  "discovery": {
   "date": "1862-Jul-16",
   "by": "Swift, Lewis",
   "site": "Marathon, New York"
  }
 },
 "tempel-tuttle": {
  "designation": "55P/Tempel-Tuttle",
  "kind": "cn",
  "orbitClass": "Halley-type Comet*",
  "epoch": 2451040.5,
  "e": 0.905552721,
  "q": 0.976427915,
  "i": 162.486575,
  "om": 235.270989,
  "w": 172.500274,
  "tp": 2450872.597734,
  "a": 10.33833823,
  "periodDays": 12141.6,
  "phys": {
   "diameterKm": 3.6,
   "albedo": 0.06
  },
  "discovery": {
   "date": "1866-Jan-06",
   "by": "Tuttle, Horace",
   "site": "Harvard College Observatory, Massachusetts"
  }
 },
 "pons-brooks": {
  "designation": "12P/Pons-Brooks",
  "kind": "cn",
  "orbitClass": "Halley-type Comet*",
  "epoch": 2460211.5,
  "e": 0.954561244,
  "q": 0.780861133,
  "i": 74.19091,
  "om": 255.855351,
  "w": 198.987999,
  "tp": 2460421.631159,
  "a": 17.184914523,
  "periodDays": 26020.7,
  "phys": {},
  "discovery": {
   "date": "1812-Jul-21",
   "by": "Pons, Jean Louis",
   "site": "Marseilles, France"
  }
 },
 "wild-2": {
  "designation": "81P/Wild 2",
  "kind": "cn",
  "orbitClass": "Jupiter-family Comet",
  "epoch": 2458808.5,
  "e": 0.537398907,
  "q": 1.595856073,
  "i": 3.237004,
  "om": 136.110221,
  "w": 41.725231,
  "tp": 2459929.28458,
  "a": 3.449745577,
  "periodDays": 2340.3,
  "phys": {
   "diameterKm": 4
  },
  "discovery": {
   "date": "1978-Jan-06",
   "by": "Wild, Paul",
   "site": "Astronomical Institute of Berne, Switzerland"
  }
 },
 "hale-bopp": {
  "designation": "C/1995 O1 (Hale-Bopp)",
  "kind": "cu",
  "orbitClass": "Comet",
  "epoch": 2459837.5,
  "e": 0.994981003,
  "q": 0.890537664,
  "i": 89.287594,
  "om": 282.733421,
  "w": 130.414667,
  "tp": 2450537.134907,
  "a": 177.433383912,
  "periodDays": 863279.5,
  "phys": {
   "diameterKm": 60,
   "albedo": 0.04
  }
 },
 "hyakutake": {
  "designation": "C/1996 B2 (Hyakutake)",
  "kind": "cu",
  "orbitClass": "Comet",
  "epoch": 2450157.5,
  "e": 0.999891647,
  "q": 0.230223531,
  "i": 124.922049,
  "om": 188.045132,
  "w": 130.175121,
  "tp": 2450204.894145,
  "a": 2124.755444394,
  "periodDays": 35773534.6,
  "phys": {
   "diameterKm": 4.2
  }
 },
 "neowise": {
  "designation": "C/2020 F3 (NEOWISE)",
  "kind": "cu",
  "orbitClass": "Comet",
  "epoch": 2459036.5,
  "e": 0.999178026,
  "q": 0.294651249,
  "i": 128.937503,
  "om": 61.010428,
  "w": 37.278658,
  "tp": 2459034.178898,
  "a": 358.467956553,
  "periodDays": 2478985.2,
  "phys": {}
 },
 "tsuchinshan-atlas": {
  "designation": "C/2023 A3 (Tsuchinshan-ATLAS)",
  "kind": "cu",
  "orbitClass": "Hyperbolic Comet",
  "epoch": 2460448.5,
  "e": 1.000095369,
  "q": 0.391430075,
  "i": 139.112109,
  "om": 21.559479,
  "w": 308.491765,
  "tp": 2460581.240845,
  "a": -4104.394095059,
  "phys": {}
 },
 "oumuamua": {
  "designation": "'Oumuamua (A/2017 U1)",
  "kind": "au",
  "orbitClass": "Hyperbolic Asteroid",
  "epoch": 2458080.5,
  "e": 1.201133796,
  "q": 0.255911581,
  "i": 122.741706,
  "om": 24.59691,
  "w": 241.810536,
  "tp": 2458006.007321,
  "a": -1.272345007,
  "phys": {
   "rotationHours": 7.937,
   "H": 22.08
  }
 },
 "borisov": {
  "designation": "C/2019 Q4 (Borisov)",
  "kind": "cu",
  "orbitClass": "Hyperbolic Comet",
  "epoch": 2458853.5,
  "e": 3.356475783,
  "q": 2.006520879,
  "i": 44.052642,
  "om": 308.147729,
  "w": 209.123686,
  "tp": 2458826.052846,
  "a": -0.851492255,
  "phys": {}
 },
 "atlas-3i": {
  "designation": "C/2025 N1 (ATLAS)",
  "kind": "cu",
  "orbitClass": "Hyperbolic Comet",
  "epoch": 2461090.5,
  "e": 6.141351449,
  "q": 1.356481057,
  "i": 175.116457,
  "om": 322.169609,
  "w": 128.02287,
  "tp": 2460977.995263,
  "a": -0.26383745,
  "phys": {}
 }
};

export const MOON_ORBITS: Record<string, MoonOrbit> = {
 "phobos": {
  "epoch": 2461041.5,
  "aKm": 9378,
  "e": 0.015488,
  "i": 27.417627,
  "om": 81.083806,
  "dOm": -0.011429496,
  "w": 159.832658,
  "dW": 0.495369776,
  "L": 252.119927,
  "dL": 1128.845767442
 },
 "deimos": {
  "epoch": 2461041.5,
  "aKm": 23459,
  "e": 0.000346,
  "i": 24.172934,
  "om": 81.227551,
  "dOm": 0.001639245,
  "w": 28.031632,
  "dW": 0,
  "L": 60.42464,
  "dL": 285.161869513
 },
 "io": {
  "epoch": 2461041.5,
  "aKm": 422029,
  "e": 0.003988,
  "i": 2.206524,
  "om": 338.480702,
  "dOm": 0.000558088,
  "w": 255.081394,
  "dW": 0,
  "L": 331.071025,
  "dL": 203.488961427
 },
 "europa": {
  "epoch": 2461041.5,
  "aKm": 671310,
  "e": 0.009286,
  "i": 2.150428,
  "om": 325.935328,
  "dOm": -0.000013868,
  "w": 76.303831,
  "dW": 0,
  "L": 277.881592,
  "dL": 101.374554757
 },
 "ganymede": {
  "epoch": 2461041.5,
  "aKm": 1070854,
  "e": 0.002186,
  "i": 2.339045,
  "om": 339.230546,
  "dOm": -0.00046664,
  "w": 338.525016,
  "dW": 0,
  "L": 341.133285,
  "dL": 50.317694593
 },
 "callisto": {
  "epoch": 2461041.5,
  "aKm": 1882640,
  "e": 0.007347,
  "i": 1.951618,
  "om": 336.702837,
  "dOm": -0.000251912,
  "w": 33.21224,
  "dW": 0,
  "L": 88.843592,
  "dL": 21.571119612
 },
 "amalthea": {
  "epoch": 2461041.5,
  "aKm": 181997,
  "e": 0.006756,
  "i": 2.283773,
  "om": 328.383947,
  "dOm": -0.023029807,
  "w": 238.256414,
  "dW": 0,
  "L": 203.942252,
  "dL": 722.631767175
 },
 "mimas": {
  "epoch": 2461041.5,
  "aKm": 186023,
  "e": 0.020401,
  "i": 29.627626,
  "om": 169.604965,
  "dOm": -0.054825485,
  "w": 258.270807,
  "dW": -0.39481356,
  "L": 137.83417,
  "dL": 381.995640067
 },
 "enceladus": {
  "epoch": 2461041.5,
  "aKm": 238411,
  "e": 0.005043,
  "i": 28.052723,
  "om": 169.514762,
  "dOm": -0.000047538,
  "w": 82.524585,
  "dW": 0,
  "L": 185.107053,
  "dL": 262.731384057
 },
 "tethys": {
  "epoch": 2461041.5,
  "aKm": 294975,
  "e": 0.001117,
  "i": 27.209819,
  "om": 171.027238,
  "dOm": 0.006047086,
  "w": 316.649894,
  "dW": 0,
  "L": 122.907702,
  "dL": 190.698076118
 },
 "dione": {
  "epoch": 2461041.5,
  "aKm": 377653,
  "e": 0.00164,
  "i": 28.024558,
  "om": 169.529581,
  "dOm": 0.000075113,
  "w": 256.911665,
  "dW": 0,
  "L": 227.961532,
  "dL": 131.534968321
 },
 "rhea": {
  "epoch": 2461041.5,
  "aKm": 527214,
  "e": 0.000883,
  "i": 28.24261,
  "om": 170.034474,
  "dOm": -0.000219944,
  "w": 157.314029,
  "dW": 0,
  "L": 238.319743,
  "dL": 79.690011656
 },
 "titan": {
  "epoch": 2461041.5,
  "aKm": 1221941,
  "e": 0.028812,
  "i": 27.708961,
  "om": 169.077405,
  "dOm": 0.000009681,
  "w": 177.943399,
  "dW": -0.003698938,
  "L": 339.331326,
  "dL": 22.576965739
 },
 "hyperion": {
  "epoch": 2461041.5,
  "aKm": 1476090,
  "e": 0.094693,
  "i": 27.052594,
  "om": 169.49131,
  "dOm": 0.000081301,
  "w": 81.970491,
  "dW": -0.006542557,
  "L": 184.50591,
  "dL": 16.883107872
 },
 "iapetus": {
  "epoch": 2461041.5,
  "aKm": 3558935,
  "e": 0.029054,
  "i": 16.995309,
  "om": 138.895884,
  "dOm": 0.000350894,
  "w": 231.022672,
  "dW": 0.147390669,
  "L": 112.005583,
  "dL": 4.537961857
 },
 "phoebe": {
  "epoch": 2461041.5,
  "aKm": 12898258,
  "e": 0.181587,
  "i": 172.80704,
  "om": 271.041548,
  "dOm": -0.007824263,
  "w": 11.815747,
  "dW": -0.068296498,
  "L": 63.810607,
  "dL": 0.658722228
 },
 "miranda": {
  "epoch": 2461041.5,
  "aKm": 129879,
  "e": 0.001331,
  "i": 99.186077,
  "om": 163.422989,
  "dOm": -0.0013926,
  "w": 55.859074,
  "dW": 0,
  "L": 315.817112,
  "dL": 254.692412564
 },
 "ariel": {
  "epoch": 2461041.5,
  "aKm": 190941,
  "e": 0.000611,
  "i": 97.715224,
  "om": 167.664537,
  "dOm": 0.000006862,
  "w": 228.239276,
  "dW": 0,
  "L": 324.504169,
  "dL": 142.835529867
 },
 "umbriel": {
  "epoch": 2461041.5,
  "aKm": 266006,
  "e": 0.004152,
  "i": 97.711472,
  "om": 167.72417,
  "dOm": 0.000003624,
  "w": 55.232678,
  "dW": 0,
  "L": 244.189324,
  "dL": 86.868892351
 },
 "titania": {
  "epoch": 2461041.5,
  "aKm": 436267,
  "e": 0.002459,
  "i": 97.763305,
  "om": 167.642249,
  "dOm": 6.16e-7,
  "w": 261.891431,
  "dW": 0,
  "L": 17.837945,
  "dL": 41.351326333
 },
 "oberon": {
  "epoch": 2461041.5,
  "aKm": 583607,
  "e": 0.0021,
  "i": 97.905594,
  "om": 167.709756,
  "dOm": -0.000001033,
  "w": 156.616198,
  "dW": 0,
  "L": 286.711499,
  "dL": 26.739550183
 },
 "proteus": {
  "epoch": 2461041.5,
  "aKm": 117674,
  "e": 0.000579,
  "i": 29.059463,
  "om": 48.71128,
  "dOm": 0.000202447,
  "w": 28.684165,
  "dW": 0,
  "L": 129.608353,
  "dL": 320.765637067
 },
 "triton": {
  "epoch": 2461041.5,
  "aKm": 354766,
  "e": 0.000138,
  "i": 129.148129,
  "om": 222.662043,
  "dOm": 0.000782594,
  "w": 102.170547,
  "dW": 0,
  "L": 272.308461,
  "dL": 61.258553155
 },
 "nereid": {
  "epoch": 2461041.5,
  "aKm": 5509318,
  "e": 0.745608,
  "i": 5.033724,
  "om": 319.298131,
  "dOm": 0.000009662,
  "w": 296.83568,
  "dW": -0.007046823,
  "L": 246.182763,
  "dL": 0.999756426
 },
 "charon": {
  "epoch": 2461041.5,
  "aKm": 19596,
  "e": 0.00016,
  "i": 112.887806,
  "om": 227.393012,
  "dOm": 2.37e-7,
  "w": 172.467905,
  "dW": 0,
  "L": 115.415582,
  "dL": 56.362531073
 },
 "nix": {
  "epoch": 2461041.5,
  "aKm": 49593,
  "e": 0.021415,
  "i": 112.88343,
  "om": 227.370247,
  "dOm": -0.000028201,
  "w": 134.01571,
  "dW": 12.238075475,
  "L": 5.230266,
  "dL": 14.484154808
 },
 "hydra": {
  "epoch": 2461041.5,
  "aKm": 65120,
  "e": 0.0047,
  "i": 112.610309,
  "om": 227.385212,
  "dOm": 0.00028484,
  "w": 146.532204,
  "dW": 0,
  "L": 328.388858,
  "dL": 9.424520032
 }
};

/**
 * Index into /data/spacecraft.bin (Float32 × 7 per sample: days from J2000,
 * x, y, z in AU, vx, vy, vz in AU/day; ecliptic J2000, centred on the Sun or Earth).
 */
export const SPACECRAFT_TRACKS: Record<string, { center: "sun" | "earth"; offset: number; count: number; start: number; end: number }> = {"voyager-1":{"center":"sun","offset":0,"count":870,"start":-8152.5,"end":12757.5},"voyager-2":{"center":"sun","offset":870,"count":1026,"start":-8168.5,"end":12772.5},"pioneer-10":{"center":"sun","offset":1896,"count":834,"start":-10164.5,"end":12755.5},"pioneer-11":{"center":"sun","offset":2730,"count":903,"start":-9765.5,"end":12758.5},"new-horizons":{"center":"sun","offset":3633,"count":423,"start":2210.5,"end":12771.5},"cassini":{"center":"sun","offset":4056,"count":3638,"start":-807.5,"end":6466.5},"juno":{"center":"sun","offset":7694,"count":3133,"start":4234.5,"end":10498.5},"europa-clipper":{"center":"sun","offset":10827,"count":1135,"start":9053.5,"end":11321.5},"parker-solar-probe":{"center":"sun","offset":11962,"count":2080,"start":6798.5,"end":10956.5},"jwst":{"center":"earth","offset":14042,"count":2929,"start":8029.5,"end":10957.5}};

export const SATELLITES = {
 "epoch": 2461309.57811,
 "count": 14420,
 "counts": [
  22,
  11133,
  651,
  1854,
  169,
  572,
  19
 ],
 "tles": {
  "iss": {
   "norad": 25544,
   "line1": "1 25544U 98067A   26268.17397659  .00011139  00000+0  20797-3 0  9993",
   "line2": "2 25544  51.6316 165.2379 0004773 179.0895 181.0103 15.49282084587251"
  },
  "tiangong": {
   "norad": 48274,
   "line1": "1 48274U 21035A   26268.14703992  .00015428  00000+0  18724-3 0  9999",
   "line2": "2 48274  41.4679  75.0253 0002138 306.5316  53.5325 15.60268422308772"
  },
  "hubble": {
   "norad": 20580,
   "line1": "1 20580U 90037B   26266.94713825  .00005513  00000+0  16734-3 0  9992",
   "line2": "2 20580  28.4727 125.0661 0001663 151.6515 208.4172 15.31734421803723"
  }
 },
 "fetched": "2026-09-25"
} as const;
